### ISSUE TITLE
`Runner` が `Game.raiseEvent()` をする状態では `GameContext.advance()` を使用しないよう、ドキュメンテーションしてほしい

### ISSUE THREAD

**Issue by yasshi2525** [akashic-games/headless-akashic#97]
マルチプレイゲームのような `GameContext` に紐づくインスタンスが `Game.raiseEvent()` する場合、 `active` なインスタンスはできるだけ早くイベントをハンドリングしたほうが、ニコ生環境や `akashic serve` 環境と近い挙動をするかと思います。

ただ、現状の `GameContext.advance()` の実装は下記のようにインスタンス毎に `advance` させるため、特に `passive` なインスタンスが `advance` 中に `Game.raiseEvent()` しても、`active` なインスタンスはすでに  `advance` し切っているため、イベントハンドリングされるのは次回 `step()` または `advance()` したときになるかと思います。

```typescript
	/**
	 * GameContext の状態を指定ミリ秒だけ進める。
	 * @param ms 進めるミリ秒
	 */
	async advance(ms: number): Promise<void> {
		const { runnerManager } = this;
		const runners = runnerManager.getRunners();
		for (let i = 0; i < runners.length; i++) {
			await runners[i].advance(ms);
		}
	}
```

現状の説明からはこの仕様が読み取れないため、`createPassiveGameClient()` を使って作成したインスタンスが `Game.raiseEvent()` をする状態で本メソッドを利用しても、イベントハンドリングされない点を注意事項として追記していただきたいです。

**Comment by xnv** [comment]
ありがとうございます。本件 #99 でご指摘のコメントを追加します。

併せて次バージョン (v4.5.0) で `GameContext#advanceEach(ms: number): void` を追加します。こちらはプレイ内の各インスタンスを並列に 1 フレームずつ進めるもので、今回のような用途でご利用いただけます。
