### ISSUE TITLE
`scaleX` または `scaleY` が `0` の `Sprite` がレンダリングされると、それ以降 `GameClient.getPrimarySurfaceCanvas()` の返す結果が変化しなくなる

### ISSUE THREAD

**Issue by yasshi2525** [akashic-games/headless-akashic#98]
`scaleX` または `scaleY` が `0` の `Sprite` がレンダリング対象になると、 `GameContext` の `step()` または `advance()` を実行しても、当該 `Sprite` のレンダリング直前の `tick` でのレンダリング内容が返されます。

ニコ生環境や `akashic serve` では `scaleX` または `scaleY` が `0` の `Sprite` を描画しても動作する点、 `akashic-engine` でも明示的に `0` を禁止していないことから、 `GameClient.getPrimarySurfaceCanvas()` でも同様の動作がなされることが望ましいかと思います。少なくとも利用時の注意事項として記載しても良いのではないかと思います。

**Comment by yasshi2525** [comment]
`node-canvas` の仕様かもしれませんが、 `width` `height` が `0` の `E` だと out of memory になりました

**Comment by xnv** [comment]
本件 https://github.com/akashic-games/headless-driver/pull/642 で修正を済ませています。
headless-akashic の内部モジュールのため、最新の headless-akashic をインストールいただくと修正後のバージョンがご利用いただけます。(既にインストールしてある環境では、一度削除して再インストールをお願いします)
